### ISSUE TITLE
Parsing OpenAI takes 57 seconds

### ISSUE THREAD

**Issue by nomisRev** [krzema12/snakeyaml-engine-kmp#204] opened 2024-06-26 13:22 UTC
Hi all,

Thank you all for the amazing work on both snakeyaml-engine-kmp, and integrating it into KAML 👏 👏 
I was testing KAML for parsing OpenAI's OpenAPI yaml file, and this took 57 seconds compared to ~110 milliseconds using SnakeYAML.

Not entire sure if it's due to `allowAnchorsAndAliases`, because other YAML's seem to work quite fast. I've not done extensive testing, or performance testing.

**Comment by krzema12** [comment] 2024-06-26 13:29
Hi @nomisRev!

Thanks for reporting this. Do you have an example YAML file where it reproduces?

**Comment by krzema12** [comment] 2024-06-26 13:55
Ok, I've reread what you wrote and understood it's about https://github.com/openai/openai-openapi/blob/master/openapi.yaml

**Comment by krzema12** [comment] 2024-06-26 14:19
@nomisRev actually, can I ask you to prepare a minimal reproducer? Since you use this lib through kaml, I'm wondering if you're trying to map the YAML into a structure of `@Serialized` classes, or in another way. A simple reproducer would disambiguate it.

**Comment by aSemy** [comment] 2024-06-26 16:01
SnakeKMP required some changes in Kaml, so it's possible we introduced a bug on the Kaml side. It'd be good to find out if Kaml is slow, or SnakeKMP.

**Comment by nomisRev** [comment] 2024-06-26 17:08
I am going to create a reproducer with the information I got here 👍 I'll report back soon.

@krzema12 No, I was deserialising into `YamlNode` (for now).

**Comment by nomisRev** [comment] 2024-06-26 20:35
I was not entirely sure how to reproduce it without KAML. Seems all the methods are quite low-level 😅 Didn't have time to get that deep. https://github.com/nomisRev/snakeyaml-kmp-reproducer

> OpenAI and OpenAPI look alike when reading too fast!

Haha, it has caused me quite a lot of confusion too!

**Comment by krzema12** [comment] 2024-06-26 21:34
Thanks @nomisRev!

From my initial tests, something interesting emerges: the regression happened in kaml 0.60.0, not in 0.58.0 where we switched to snakeyaml-engine-kmp. In 0.60.0, this changed ([ref](https://github.com/charleskorn/kaml/releases/tag/0.60.0)):

> Updated: build with Kotlin 2.0.0
> Updated: use snakeyaml-engine-kmp 3.0.0
> Updated: use kotlinx-serialization 1.7.0

In snakeyaml-engine-kmp [3.0.0](https://github.com/krzema12/snakeyaml-engine-kmp/releases/tag/v3.0.0), we released lots of pieces of refactoring that, well, by definition shouldn't affect correctness or performance, but we should double-check it. Or maybe the regression comes from the other two Kotlin-related changes, that would be interesting.

I'm gonna be offline for the next 2-3 weeks, so won't be able to dig into it, but @aSemy if you have capacity - would be cool to understand what happened. If not, I'll revisit once I'm back.

**Comment by krzema12** [comment] 2024-06-26 22:03
FWIW, here's what I see in CPU sampler (VisualVM) for 0.59.0 - isn't that helpful, probably something's off with sampling rate but couldn't sort it out:

<img width="1357" alt="Screenshot 2024-06-26 at 23 56 40" src="https://github.com/krzema12/snakeyaml-engine-kmp/assets/3110813/b8f52ba5-7b98-45c8-9744-ceb254eec652">

but for 0.60.0 it's much more interesting:

<img width="1418" alt="Screenshot 2024-06-26 at 23 55 06" src="https://github.com/krzema12/snakeyaml-engine-kmp/assets/3110813/00d21ee7-b555-47d8-bf27-4a15d11ad503">
<img width="1172" alt="Screenshot 2024-06-26 at 23 55 20" src="https://github.com/krzema12/snakeyaml-engine-kmp/assets/3110813/d4ca045a-1c76-479c-a5b4-9efbf23748e8">

**Comment by krzema12** [comment] 2024-06-26 22:06
@aSemy could it be caused by [Refactor Mark](https://github.com/krzema12/snakeyaml-engine-kmp/pull/182) and "Change codepoint buffer from mutable `IntArray` to read-only `List<Int>`"?

**Comment by nomisRev** [comment] 2024-06-27 07:09
Thank you for the blazing fast replies 🙏 Enjoy your downtime @krzema12! ☺️

@aSemy let me know if I can provide any other info.

**Comment by aSemy** [comment] 2024-06-28 06:07
> @aSemy could it be caused by [Refactor Mark](https://github.com/krzema12/snakeyaml-engine-kmp/pull/182) and "Change codepoint buffer from mutable `IntArray` to read-only `List<Int>`"?

Yes, that makes sense. Instead of making a read-only copy instead it should probably create a read-only wrapper around the original data, without copying it.

I'm not sure when I'll be able to have a look...

As a workaround, SnakeKMP has an option to disable marks, which should prevent this problem. But I don't think that Kaml has exposed a way of configuring it.

**Comment by OptimumCode** [comment] 2024-06-28 11:13
I think I could take a look at it. I will implement a read-only wrapper and check how it performs with the changes

**Comment by OptimumCode** [comment] 2024-06-28 11:30
I tried to read the [openai.yaml](https://github.com/nomisRev/OpenAPI-kt/blob/main/parser/src/jvmTest/resources/openai.yaml) from https://github.com/nomisRev/OpenAPI-kt repo using Kaml and updated version of snakeyaml-engine-kmp.

A simple read-only wrapper helped a lot but it still performs much slower than an array.

I will try one more thing and update the comment with the results.

For now, this is the code sample I used for measurements (probably it worth adding a benchmark to the repo - will also look into it):

<details>
<summary>Code</summary>

```kotlin
val resource =
      Files.newBufferedReader(file).use(Reader::readText)
val yaml =
  Yaml(
    configuration =
      YamlConfiguration(
        allowAnchorsAndAliases = true
      )
  )
val time =
  measureTime {
    val node = yaml.parseToYamlNode(resource)
    println(node::class.simpleName)
  }
println("Done in $time")
```
</details>

These are the results I got

| State | Time |
|--------|--------|
| Current | 3m 19.7s |
| IntArray | 273.5ms |
| Read-only wrapper based on AbstractList | 7.1s |

<details>
<summary>Read-only wrapper based on AbstractList</summary>

```kotlin
internal class ReadOnlyIntArrayToListAdapter(
    private val array: IntArray,
) : AbstractList<Int>() {

    override val size: Int
        get() = array.size

    override fun get(index: Int): Int = array[index]
}
```
</details>

**Comment by krzema12** [comment] 2024-07-14 20:36
The fix has been released in [v3.0.1](https://github.com/krzema12/snakeyaml-engine-kmp/releases/tag/v3.0.1), let's wait until kaml uses this version to confirm it works properly end-to-end.

**Comment by krzema12** [comment] 2024-07-28 11:28
@nomisRev ready to test if the performance regression is gone: https://github.com/charleskorn/kaml/releases/tag/0.61.0, please let us know!

**Comment by krzema12** [comment] 2024-08-03 04:45
Let me resolve it, and we'll reopen if needed.

**Closed by krzema12** 2024-08-03 04:45 UTC
